[package]
name = "mars-cli"
version = "0.5.6"
description = "A command line interface for the Mars program."
license = "Apache-2.0"
edition = "2021"

[[bin]]
name = "mars"
path = "src/main.rs"

[features]
default = []
admin = []

[dependencies]
bincode = "1.3.3"
bs58 = "0.5.1"
cached = "0.46.1"
chrono = "0.4.34"
clap = { version = "4.4.12", features = ["derive"] }
futures = "0.3.30"
log = "0.4"
mars = { version = "1.0.0", package = "mars-program" }
rand = "0.8.4"
rodio = "0.17.3"
solana-cli-config = "1.18.5"
solana-client = "^1.16"
solana-program = "^1.16"
solana-sdk = "^1.16"
solana-transaction-status = "^1.16"
spl-token = { version = "^4", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "^2.2", features = [ "no-entrypoint" ] }
tokio = "1.35.1"
